/**
 * Complete list of countries/territories for the country picker.
 * Sorted alphabetically. Each entry is a plain string.
 */
export const COUNTRIES = [
  'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
  'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia', 'Austria',
  'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados',
  'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
  'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei',
  'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia',
  'Cameroon', 'Canada', 'Central African Republic', 'Chad', 'Chile',
  'China', 'Colombia', 'Comoros', 'Congo (DRC)', 'Congo (Republic)',
  'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic',
  'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador',
  'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
  'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France',
  'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana',
  'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau',
  'Guyana', 'Haiti', 'Honduras', 'Hungary', 'Iceland',
  'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland',
  'Israel', 'Italy', 'Ivory Coast', 'Jamaica', 'Japan',
  'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kosovo',
  'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon',
  'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania',
  'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives',
  'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius',
  'Mexico', 'Micronesia', 'Moldova', 'Monaco', 'Mongolia',
  'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia',
  'Nauru', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua',
  'Niger', 'Nigeria', 'North Korea', 'North Macedonia', 'Norway',
  'Oman', 'Pakistan', 'Palau', 'Palestine', 'Panama',
  'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland',
  'Portugal', 'Puerto Rico', 'Qatar', 'Romania', 'Russia',
  'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa',
  'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
  'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
  'Solomon Islands', 'Somalia', 'South Africa', 'South Korea', 'South Sudan',
  'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden',
  'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania',
  'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago',
  'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu', 'Uganda',
  'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay',
  'Uzbekistan', 'Vanuatu', 'Vatican City', 'Venezuela', 'Vietnam',
  'Yemen', 'Zambia', 'Zimbabwe',
];

// Localized display names, keyed by the canonical English name → per-language.
// The canonical English name is what gets STORED (stable, so aggregation later
// isn't broken by language); only the DISPLAY is translated. Missing entries or
// languages fall back to the English name.
export const COUNTRY_I18N = {
  'Afghanistan': { es: 'Afganistán', pt: 'Afeganistão', fr: 'Afghanistan', de: 'Afghanistan', it: 'Afghanistan' },
  'Albania': { es: 'Albania', pt: 'Albânia', fr: 'Albanie', de: 'Albanien', it: 'Albania' },
  'Algeria': { es: 'Argelia', pt: 'Argélia', fr: 'Algérie', de: 'Algerien', it: 'Algeria' },
  'Andorra': { es: 'Andorra', pt: 'Andorra', fr: 'Andorre', de: 'Andorra', it: 'Andorra' },
  'Angola': { es: 'Angola', pt: 'Angola', fr: 'Angola', de: 'Angola', it: 'Angola' },
  'Antigua and Barbuda': { es: 'Antigua y Barbuda', pt: 'Antígua e Barbuda', fr: 'Antigua-et-Barbuda', de: 'Antigua und Barbuda', it: 'Antigua e Barbuda' },
  'Argentina': { es: 'Argentina', pt: 'Argentina', fr: 'Argentine', de: 'Argentinien', it: 'Argentina' },
  'Armenia': { es: 'Armenia', pt: 'Armênia', fr: 'Arménie', de: 'Armenien', it: 'Armenia' },
  'Australia': { es: 'Australia', pt: 'Austrália', fr: 'Australie', de: 'Australien', it: 'Australia' },
  'Austria': { es: 'Austria', pt: 'Áustria', fr: 'Autriche', de: 'Österreich', it: 'Austria' },
  'Azerbaijan': { es: 'Azerbaiyán', pt: 'Azerbaijão', fr: 'Azerbaïdjan', de: 'Aserbaidschan', it: 'Azerbaigian' },
  'Bahamas': { es: 'Bahamas', pt: 'Bahamas', fr: 'Bahamas', de: 'Bahamas', it: 'Bahamas' },
  'Bahrain': { es: 'Baréin', pt: 'Bahrein', fr: 'Bahreïn', de: 'Bahrain', it: 'Bahrein' },
  'Bangladesh': { es: 'Bangladés', pt: 'Bangladesh', fr: 'Bangladesh', de: 'Bangladesch', it: 'Bangladesh' },
  'Barbados': { es: 'Barbados', pt: 'Barbados', fr: 'Barbade', de: 'Barbados', it: 'Barbados' },
  'Belarus': { es: 'Bielorrusia', pt: 'Bielorrússia', fr: 'Biélorussie', de: 'Belarus', it: 'Bielorussia' },
  'Belgium': { es: 'Bélgica', pt: 'Bélgica', fr: 'Belgique', de: 'Belgien', it: 'Belgio' },
  'Belize': { es: 'Belice', pt: 'Belize', fr: 'Belize', de: 'Belize', it: 'Belize' },
  'Benin': { es: 'Benín', pt: 'Benin', fr: 'Bénin', de: 'Benin', it: 'Benin' },
  'Bhutan': { es: 'Bután', pt: 'Butão', fr: 'Bhoutan', de: 'Bhutan', it: 'Bhutan' },
  'Bolivia': { es: 'Bolivia', pt: 'Bolívia', fr: 'Bolivie', de: 'Bolivien', it: 'Bolivia' },
  'Bosnia and Herzegovina': { es: 'Bosnia y Herzegovina', pt: 'Bósnia e Herzegovina', fr: 'Bosnie-Herzégovine', de: 'Bosnien und Herzegowina', it: 'Bosnia ed Erzegovina' },
  'Botswana': { es: 'Botsuana', pt: 'Botsuana', fr: 'Botswana', de: 'Botswana', it: 'Botswana' },
  'Brazil': { es: 'Brasil', pt: 'Brasil', fr: 'Brésil', de: 'Brasilien', it: 'Brasile' },
  'Brunei': { es: 'Brunéi', pt: 'Brunei', fr: 'Brunei', de: 'Brunei', it: 'Brunei' },
  'Bulgaria': { es: 'Bulgaria', pt: 'Bulgária', fr: 'Bulgarie', de: 'Bulgarien', it: 'Bulgaria' },
  'Burkina Faso': { es: 'Burkina Faso', pt: 'Burquina Faso', fr: 'Burkina Faso', de: 'Burkina Faso', it: 'Burkina Faso' },
  'Burundi': { es: 'Burundi', pt: 'Burundi', fr: 'Burundi', de: 'Burundi', it: 'Burundi' },
  'Cabo Verde': { es: 'Cabo Verde', pt: 'Cabo Verde', fr: 'Cap-Vert', de: 'Kap Verde', it: 'Capo Verde' },
  'Cambodia': { es: 'Camboya', pt: 'Camboja', fr: 'Cambodge', de: 'Kambodscha', it: 'Cambogia' },
  'Cameroon': { es: 'Camerún', pt: 'Camarões', fr: 'Cameroun', de: 'Kamerun', it: 'Camerun' },
  'Canada': { es: 'Canadá', pt: 'Canadá', fr: 'Canada', de: 'Kanada', it: 'Canada' },
  'Central African Republic': { es: 'República Centroafricana', pt: 'República Centro-Africana', fr: 'République centrafricaine', de: 'Zentralafrikanische Republik', it: 'Repubblica Centrafricana' },
  'Chad': { es: 'Chad', pt: 'Chade', fr: 'Tchad', de: 'Tschad', it: 'Ciad' },
  'Chile': { es: 'Chile', pt: 'Chile', fr: 'Chili', de: 'Chile', it: 'Cile' },
  'China': { es: 'China', pt: 'China', fr: 'Chine', de: 'China', it: 'Cina' },
  'Colombia': { es: 'Colombia', pt: 'Colômbia', fr: 'Colombie', de: 'Kolumbien', it: 'Colombia' },
  'Comoros': { es: 'Comoras', pt: 'Comores', fr: 'Comores', de: 'Komoren', it: 'Comore' },
  'Congo (DRC)': { es: 'República Democrática del Congo', pt: 'República Democrática do Congo', fr: 'République démocratique du Congo', de: 'Demokratische Republik Kongo', it: 'Repubblica Democratica del Congo' },
  'Congo (Republic)': { es: 'República del Congo', pt: 'República do Congo', fr: 'République du Congo', de: 'Republik Kongo', it: 'Repubblica del Congo' },
  'Costa Rica': { es: 'Costa Rica', pt: 'Costa Rica', fr: 'Costa Rica', de: 'Costa Rica', it: 'Costa Rica' },
  'Croatia': { es: 'Croacia', pt: 'Croácia', fr: 'Croatie', de: 'Kroatien', it: 'Croazia' },
  'Cuba': { es: 'Cuba', pt: 'Cuba', fr: 'Cuba', de: 'Kuba', it: 'Cuba' },
  'Cyprus': { es: 'Chipre', pt: 'Chipre', fr: 'Chypre', de: 'Zypern', it: 'Cipro' },
  'Czech Republic': { es: 'República Checa', pt: 'República Tcheca', fr: 'République tchèque', de: 'Tschechien', it: 'Repubblica Ceca' },
  'Denmark': { es: 'Dinamarca', pt: 'Dinamarca', fr: 'Danemark', de: 'Dänemark', it: 'Danimarca' },
  'Djibouti': { es: 'Yibuti', pt: 'Djibuti', fr: 'Djibouti', de: 'Dschibuti', it: 'Gibuti' },
  'Dominica': { es: 'Dominica', pt: 'Dominica', fr: 'Dominique', de: 'Dominica', it: 'Dominica' },
  'Dominican Republic': { es: 'República Dominicana', pt: 'República Dominicana', fr: 'République dominicaine', de: 'Dominikanische Republik', it: 'Repubblica Dominicana' },
  'Ecuador': { es: 'Ecuador', pt: 'Equador', fr: 'Équateur', de: 'Ecuador', it: 'Ecuador' },
  'Egypt': { es: 'Egipto', pt: 'Egito', fr: 'Égypte', de: 'Ägypten', it: 'Egitto' },
  'El Salvador': { es: 'El Salvador', pt: 'El Salvador', fr: 'Salvador', de: 'El Salvador', it: 'El Salvador' },
  'Equatorial Guinea': { es: 'Guinea Ecuatorial', pt: 'Guiné Equatorial', fr: 'Guinée équatoriale', de: 'Äquatorialguinea', it: 'Guinea Equatoriale' },
  'Eritrea': { es: 'Eritrea', pt: 'Eritreia', fr: 'Érythrée', de: 'Eritrea', it: 'Eritrea' },
  'Estonia': { es: 'Estonia', pt: 'Estônia', fr: 'Estonie', de: 'Estland', it: 'Estonia' },
  'Eswatini': { es: 'Esuatini', pt: 'Essuatíni', fr: 'Eswatini', de: 'Eswatini', it: 'Eswatini' },
  'Ethiopia': { es: 'Etiopía', pt: 'Etiópia', fr: 'Éthiopie', de: 'Äthiopien', it: 'Etiopia' },
  'Fiji': { es: 'Fiyi', pt: 'Fiji', fr: 'Fidji', de: 'Fidschi', it: 'Figi' },
  'Finland': { es: 'Finlandia', pt: 'Finlândia', fr: 'Finlande', de: 'Finnland', it: 'Finlandia' },
  'France': { es: 'Francia', pt: 'França', fr: 'France', de: 'Frankreich', it: 'Francia' },
  'Gabon': { es: 'Gabón', pt: 'Gabão', fr: 'Gabon', de: 'Gabun', it: 'Gabon' },
  'Gambia': { es: 'Gambia', pt: 'Gâmbia', fr: 'Gambie', de: 'Gambia', it: 'Gambia' },
  'Georgia': { es: 'Georgia', pt: 'Geórgia', fr: 'Géorgie', de: 'Georgien', it: 'Georgia' },
  'Germany': { es: 'Alemania', pt: 'Alemanha', fr: 'Allemagne', de: 'Deutschland', it: 'Germania' },
  'Ghana': { es: 'Ghana', pt: 'Gana', fr: 'Ghana', de: 'Ghana', it: 'Ghana' },
  'Greece': { es: 'Grecia', pt: 'Grécia', fr: 'Grèce', de: 'Griechenland', it: 'Grecia' },
  'Grenada': { es: 'Granada', pt: 'Granada', fr: 'Grenade', de: 'Grenada', it: 'Grenada' },
  'Guatemala': { es: 'Guatemala', pt: 'Guatemala', fr: 'Guatemala', de: 'Guatemala', it: 'Guatemala' },
  'Guinea': { es: 'Guinea', pt: 'Guiné', fr: 'Guinée', de: 'Guinea', it: 'Guinea' },
  'Guinea-Bissau': { es: 'Guinea-Bisáu', pt: 'Guiné-Bissau', fr: 'Guinée-Bissau', de: 'Guinea-Bissau', it: 'Guinea-Bissau' },
  'Guyana': { es: 'Guyana', pt: 'Guiana', fr: 'Guyana', de: 'Guyana', it: 'Guyana' },
  'Haiti': { es: 'Haití', pt: 'Haiti', fr: 'Haïti', de: 'Haiti', it: 'Haiti' },
  'Honduras': { es: 'Honduras', pt: 'Honduras', fr: 'Honduras', de: 'Honduras', it: 'Honduras' },
  'Hungary': { es: 'Hungría', pt: 'Hungria', fr: 'Hongrie', de: 'Ungarn', it: 'Ungheria' },
  'Iceland': { es: 'Islandia', pt: 'Islândia', fr: 'Islande', de: 'Island', it: 'Islanda' },
  'India': { es: 'India', pt: 'Índia', fr: 'Inde', de: 'Indien', it: 'India' },
  'Indonesia': { es: 'Indonesia', pt: 'Indonésia', fr: 'Indonésie', de: 'Indonesien', it: 'Indonesia' },
  'Iran': { es: 'Irán', pt: 'Irã', fr: 'Iran', de: 'Iran', it: 'Iran' },
  'Iraq': { es: 'Irak', pt: 'Iraque', fr: 'Irak', de: 'Irak', it: 'Iraq' },
  'Ireland': { es: 'Irlanda', pt: 'Irlanda', fr: 'Irlande', de: 'Irland', it: 'Irlanda' },
  'Israel': { es: 'Israel', pt: 'Israel', fr: 'Israël', de: 'Israel', it: 'Israele' },
  'Italy': { es: 'Italia', pt: 'Itália', fr: 'Italie', de: 'Italien', it: 'Italia' },
  'Ivory Coast': { es: 'Costa de Marfil', pt: 'Costa do Marfim', fr: 'Côte d\'Ivoire', de: 'Elfenbeinküste', it: 'Costa d\'Avorio' },
  'Jamaica': { es: 'Jamaica', pt: 'Jamaica', fr: 'Jamaïque', de: 'Jamaika', it: 'Giamaica' },
  'Japan': { es: 'Japón', pt: 'Japão', fr: 'Japon', de: 'Japan', it: 'Giappone' },
  'Jordan': { es: 'Jordania', pt: 'Jordânia', fr: 'Jordanie', de: 'Jordanien', it: 'Giordania' },
  'Kazakhstan': { es: 'Kazajistán', pt: 'Cazaquistão', fr: 'Kazakhstan', de: 'Kasachstan', it: 'Kazakistan' },
  'Kenya': { es: 'Kenia', pt: 'Quênia', fr: 'Kenya', de: 'Kenia', it: 'Kenya' },
  'Kiribati': { es: 'Kiribati', pt: 'Kiribati', fr: 'Kiribati', de: 'Kiribati', it: 'Kiribati' },
  'Kosovo': { es: 'Kosovo', pt: 'Kosovo', fr: 'Kosovo', de: 'Kosovo', it: 'Kosovo' },
  'Kuwait': { es: 'Kuwait', pt: 'Kuwait', fr: 'Koweït', de: 'Kuwait', it: 'Kuwait' },
  'Kyrgyzstan': { es: 'Kirguistán', pt: 'Quirguistão', fr: 'Kirghizistan', de: 'Kirgisistan', it: 'Kirghizistan' },
  'Laos': { es: 'Laos', pt: 'Laos', fr: 'Laos', de: 'Laos', it: 'Laos' },
  'Latvia': { es: 'Letonia', pt: 'Letônia', fr: 'Lettonie', de: 'Lettland', it: 'Lettonia' },
  'Lebanon': { es: 'Líbano', pt: 'Líbano', fr: 'Liban', de: 'Libanon', it: 'Libano' },
  'Lesotho': { es: 'Lesoto', pt: 'Lesoto', fr: 'Lesotho', de: 'Lesotho', it: 'Lesotho' },
  'Liberia': { es: 'Liberia', pt: 'Libéria', fr: 'Liberia', de: 'Liberia', it: 'Liberia' },
  'Libya': { es: 'Libia', pt: 'Líbia', fr: 'Libye', de: 'Libyen', it: 'Libia' },
  'Liechtenstein': { es: 'Liechtenstein', pt: 'Liechtenstein', fr: 'Liechtenstein', de: 'Liechtenstein', it: 'Liechtenstein' },
  'Lithuania': { es: 'Lituania', pt: 'Lituânia', fr: 'Lituanie', de: 'Litauen', it: 'Lituania' },
  'Luxembourg': { es: 'Luxemburgo', pt: 'Luxemburgo', fr: 'Luxembourg', de: 'Luxemburg', it: 'Lussemburgo' },
  'Madagascar': { es: 'Madagascar', pt: 'Madagascar', fr: 'Madagascar', de: 'Madagaskar', it: 'Madagascar' },
  'Malawi': { es: 'Malaui', pt: 'Malawi', fr: 'Malawi', de: 'Malawi', it: 'Malawi' },
  'Malaysia': { es: 'Malasia', pt: 'Malásia', fr: 'Malaisie', de: 'Malaysia', it: 'Malaysia' },
  'Maldives': { es: 'Maldivas', pt: 'Maldivas', fr: 'Maldives', de: 'Malediven', it: 'Maldive' },
  'Mali': { es: 'Mali', pt: 'Mali', fr: 'Mali', de: 'Mali', it: 'Mali' },
  'Malta': { es: 'Malta', pt: 'Malta', fr: 'Malte', de: 'Malta', it: 'Malta' },
  'Marshall Islands': { es: 'Islas Marshall', pt: 'Ilhas Marshall', fr: 'Îles Marshall', de: 'Marshallinseln', it: 'Isole Marshall' },
  'Mauritania': { es: 'Mauritania', pt: 'Mauritânia', fr: 'Mauritanie', de: 'Mauretanien', it: 'Mauritania' },
  'Mauritius': { es: 'Mauricio', pt: 'Maurício', fr: 'Maurice', de: 'Mauritius', it: 'Mauritius' },
  'Mexico': { es: 'México', pt: 'México', fr: 'Mexique', de: 'Mexiko', it: 'Messico' },
  'Micronesia': { es: 'Micronesia', pt: 'Micronésia', fr: 'Micronésie', de: 'Mikronesien', it: 'Micronesia' },
  'Moldova': { es: 'Moldavia', pt: 'Moldávia', fr: 'Moldavie', de: 'Moldau', it: 'Moldavia' },
  'Monaco': { es: 'Mónaco', pt: 'Mônaco', fr: 'Monaco', de: 'Monaco', it: 'Monaco' },
  'Mongolia': { es: 'Mongolia', pt: 'Mongólia', fr: 'Mongolie', de: 'Mongolei', it: 'Mongolia' },
  'Montenegro': { es: 'Montenegro', pt: 'Montenegro', fr: 'Monténégro', de: 'Montenegro', it: 'Montenegro' },
  'Morocco': { es: 'Marruecos', pt: 'Marrocos', fr: 'Maroc', de: 'Marokko', it: 'Marocco' },
  'Mozambique': { es: 'Mozambique', pt: 'Moçambique', fr: 'Mozambique', de: 'Mosambik', it: 'Mozambico' },
  'Myanmar': { es: 'Myanmar', pt: 'Mianmar', fr: 'Birmanie', de: 'Myanmar', it: 'Birmania' },
  'Namibia': { es: 'Namibia', pt: 'Namíbia', fr: 'Namibie', de: 'Namibia', it: 'Namibia' },
  'Nauru': { es: 'Nauru', pt: 'Nauru', fr: 'Nauru', de: 'Nauru', it: 'Nauru' },
  'Nepal': { es: 'Nepal', pt: 'Nepal', fr: 'Népal', de: 'Nepal', it: 'Nepal' },
  'Netherlands': { es: 'Países Bajos', pt: 'Países Baixos', fr: 'Pays-Bas', de: 'Niederlande', it: 'Paesi Bassi' },
  'New Zealand': { es: 'Nueva Zelanda', pt: 'Nova Zelândia', fr: 'Nouvelle-Zélande', de: 'Neuseeland', it: 'Nuova Zelanda' },
  'Nicaragua': { es: 'Nicaragua', pt: 'Nicarágua', fr: 'Nicaragua', de: 'Nicaragua', it: 'Nicaragua' },
  'Niger': { es: 'Níger', pt: 'Níger', fr: 'Niger', de: 'Niger', it: 'Niger' },
  'Nigeria': { es: 'Nigeria', pt: 'Nigéria', fr: 'Nigéria', de: 'Nigeria', it: 'Nigeria' },
  'North Korea': { es: 'Corea del Norte', pt: 'Coreia do Norte', fr: 'Corée du Nord', de: 'Nordkorea', it: 'Corea del Nord' },
  'North Macedonia': { es: 'Macedonia del Norte', pt: 'Macedônia do Norte', fr: 'Macédoine du Nord', de: 'Nordmazedonien', it: 'Macedonia del Nord' },
  'Norway': { es: 'Noruega', pt: 'Noruega', fr: 'Norvège', de: 'Norwegen', it: 'Norvegia' },
  'Oman': { es: 'Omán', pt: 'Omã', fr: 'Oman', de: 'Oman', it: 'Oman' },
  'Pakistan': { es: 'Pakistán', pt: 'Paquistão', fr: 'Pakistan', de: 'Pakistan', it: 'Pakistan' },
  'Palau': { es: 'Palaos', pt: 'Palau', fr: 'Palaos', de: 'Palau', it: 'Palau' },
  'Palestine': { es: 'Palestina', pt: 'Palestina', fr: 'Palestine', de: 'Palästina', it: 'Palestina' },
  'Panama': { es: 'Panamá', pt: 'Panamá', fr: 'Panama', de: 'Panama', it: 'Panama' },
  'Papua New Guinea': { es: 'Papúa Nueva Guinea', pt: 'Papua-Nova Guiné', fr: 'Papouasie-Nouvelle-Guinée', de: 'Papua-Neuguinea', it: 'Papua Nuova Guinea' },
  'Paraguay': { es: 'Paraguay', pt: 'Paraguai', fr: 'Paraguay', de: 'Paraguay', it: 'Paraguay' },
  'Peru': { es: 'Perú', pt: 'Peru', fr: 'Pérou', de: 'Peru', it: 'Perù' },
  'Philippines': { es: 'Filipinas', pt: 'Filipinas', fr: 'Philippines', de: 'Philippinen', it: 'Filippine' },
  'Poland': { es: 'Polonia', pt: 'Polônia', fr: 'Pologne', de: 'Polen', it: 'Polonia' },
  'Portugal': { es: 'Portugal', pt: 'Portugal', fr: 'Portugal', de: 'Portugal', it: 'Portogallo' },
  'Puerto Rico': { es: 'Puerto Rico', pt: 'Porto Rico', fr: 'Porto Rico', de: 'Puerto Rico', it: 'Porto Rico' },
  'Qatar': { es: 'Catar', pt: 'Catar', fr: 'Qatar', de: 'Katar', it: 'Qatar' },
  'Romania': { es: 'Rumania', pt: 'Romênia', fr: 'Roumanie', de: 'Rumänien', it: 'Romania' },
  'Russia': { es: 'Rusia', pt: 'Rússia', fr: 'Russie', de: 'Russland', it: 'Russia' },
  'Rwanda': { es: 'Ruanda', pt: 'Ruanda', fr: 'Rwanda', de: 'Ruanda', it: 'Ruanda' },
  'Saint Kitts and Nevis': { es: 'San Cristóbal y Nieves', pt: 'São Cristóvão e Nevis', fr: 'Saint-Kitts-et-Nevis', de: 'St. Kitts und Nevis', it: 'Saint Kitts e Nevis' },
  'Saint Lucia': { es: 'Santa Lucía', pt: 'Santa Lúcia', fr: 'Sainte-Lucie', de: 'St. Lucia', it: 'Saint Lucia' },
  'Saint Vincent and the Grenadines': { es: 'San Vicente y las Granadinas', pt: 'São Vicente e Granadinas', fr: 'Saint-Vincent-et-les-Grenadines', de: 'St. Vincent und die Grenadinen', it: 'Saint Vincent e Grenadine' },
  'Samoa': { es: 'Samoa', pt: 'Samoa', fr: 'Samoa', de: 'Samoa', it: 'Samoa' },
  'San Marino': { es: 'San Marino', pt: 'San Marino', fr: 'Saint-Marin', de: 'San Marino', it: 'San Marino' },
  'Sao Tome and Principe': { es: 'Santo Tomé y Príncipe', pt: 'São Tomé e Príncipe', fr: 'Sao Tomé-et-Principe', de: 'São Tomé und Príncipe', it: 'São Tomé e Príncipe' },
  'Saudi Arabia': { es: 'Arabia Saudita', pt: 'Arábia Saudita', fr: 'Arabie saoudite', de: 'Saudi-Arabien', it: 'Arabia Saudita' },
  'Senegal': { es: 'Senegal', pt: 'Senegal', fr: 'Sénégal', de: 'Senegal', it: 'Senegal' },
  'Serbia': { es: 'Serbia', pt: 'Sérvia', fr: 'Serbie', de: 'Serbien', it: 'Serbia' },
  'Seychelles': { es: 'Seychelles', pt: 'Seicheles', fr: 'Seychelles', de: 'Seychellen', it: 'Seychelles' },
  'Sierra Leone': { es: 'Sierra Leona', pt: 'Serra Leoa', fr: 'Sierra Leone', de: 'Sierra Leone', it: 'Sierra Leone' },
  'Singapore': { es: 'Singapur', pt: 'Singapura', fr: 'Singapour', de: 'Singapur', it: 'Singapore' },
  'Slovakia': { es: 'Eslovaquia', pt: 'Eslováquia', fr: 'Slovaquie', de: 'Slowakei', it: 'Slovacchia' },
  'Slovenia': { es: 'Eslovenia', pt: 'Eslovênia', fr: 'Slovénie', de: 'Slowenien', it: 'Slovenia' },
  'Solomon Islands': { es: 'Islas Salomón', pt: 'Ilhas Salomão', fr: 'Îles Salomon', de: 'Salomonen', it: 'Isole Salomone' },
  'Somalia': { es: 'Somalia', pt: 'Somália', fr: 'Somalie', de: 'Somalia', it: 'Somalia' },
  'South Africa': { es: 'Sudáfrica', pt: 'África do Sul', fr: 'Afrique du Sud', de: 'Südafrika', it: 'Sudafrica' },
  'South Korea': { es: 'Corea del Sur', pt: 'Coreia do Sul', fr: 'Corée du Sud', de: 'Südkorea', it: 'Corea del Sud' },
  'South Sudan': { es: 'Sudán del Sur', pt: 'Sudão do Sul', fr: 'Soudan du Sud', de: 'Südsudan', it: 'Sudan del Sud' },
  'Spain': { es: 'España', pt: 'Espanha', fr: 'Espagne', de: 'Spanien', it: 'Spagna' },
  'Sri Lanka': { es: 'Sri Lanka', pt: 'Sri Lanka', fr: 'Sri Lanka', de: 'Sri Lanka', it: 'Sri Lanka' },
  'Sudan': { es: 'Sudán', pt: 'Sudão', fr: 'Soudan', de: 'Sudan', it: 'Sudan' },
  'Suriname': { es: 'Surinam', pt: 'Suriname', fr: 'Suriname', de: 'Suriname', it: 'Suriname' },
  'Sweden': { es: 'Suecia', pt: 'Suécia', fr: 'Suède', de: 'Schweden', it: 'Svezia' },
  'Switzerland': { es: 'Suiza', pt: 'Suíça', fr: 'Suisse', de: 'Schweiz', it: 'Svizzera' },
  'Syria': { es: 'Siria', pt: 'Síria', fr: 'Syrie', de: 'Syrien', it: 'Siria' },
  'Taiwan': { es: 'Taiwán', pt: 'Taiwan', fr: 'Taïwan', de: 'Taiwan', it: 'Taiwan' },
  'Tajikistan': { es: 'Tayikistán', pt: 'Tajiquistão', fr: 'Tadjikistan', de: 'Tadschikistan', it: 'Tagikistan' },
  'Tanzania': { es: 'Tanzania', pt: 'Tanzânia', fr: 'Tanzanie', de: 'Tansania', it: 'Tanzania' },
  'Thailand': { es: 'Tailandia', pt: 'Tailândia', fr: 'Thaïlande', de: 'Thailand', it: 'Thailandia' },
  'Timor-Leste': { es: 'Timor Oriental', pt: 'Timor-Leste', fr: 'Timor oriental', de: 'Osttimor', it: 'Timor Est' },
  'Togo': { es: 'Togo', pt: 'Togo', fr: 'Togo', de: 'Togo', it: 'Togo' },
  'Tonga': { es: 'Tonga', pt: 'Tonga', fr: 'Tonga', de: 'Tonga', it: 'Tonga' },
  'Trinidad and Tobago': { es: 'Trinidad y Tobago', pt: 'Trinidad e Tobago', fr: 'Trinité-et-Tobago', de: 'Trinidad und Tobago', it: 'Trinidad e Tobago' },
  'Tunisia': { es: 'Túnez', pt: 'Tunísia', fr: 'Tunisie', de: 'Tunesien', it: 'Tunisia' },
  'Turkey': { es: 'Turquía', pt: 'Turquia', fr: 'Turquie', de: 'Türkei', it: 'Turchia' },
  'Turkmenistan': { es: 'Turkmenistán', pt: 'Turcomenistão', fr: 'Turkménistan', de: 'Turkmenistan', it: 'Turkmenistan' },
  'Tuvalu': { es: 'Tuvalu', pt: 'Tuvalu', fr: 'Tuvalu', de: 'Tuvalu', it: 'Tuvalu' },
  'Uganda': { es: 'Uganda', pt: 'Uganda', fr: 'Ouganda', de: 'Uganda', it: 'Uganda' },
  'Ukraine': { es: 'Ucrania', pt: 'Ucrânia', fr: 'Ukraine', de: 'Ukraine', it: 'Ucraina' },
  'United Arab Emirates': { es: 'Emiratos Árabes Unidos', pt: 'Emirados Árabes Unidos', fr: 'Émirats arabes unis', de: 'Vereinigte Arabische Emirate', it: 'Emirati Arabi Uniti' },
  'United Kingdom': { es: 'Reino Unido', pt: 'Reino Unido', fr: 'Royaume-Uni', de: 'Vereinigtes Königreich', it: 'Regno Unito' },
  'United States': { es: 'Estados Unidos', pt: 'Estados Unidos', fr: 'États-Unis', de: 'Vereinigte Staaten', it: 'Stati Uniti' },
  'Uruguay': { es: 'Uruguay', pt: 'Uruguai', fr: 'Uruguay', de: 'Uruguay', it: 'Uruguay' },
  'Uzbekistan': { es: 'Uzbekistán', pt: 'Uzbequistão', fr: 'Ouzbékistan', de: 'Usbekistan', it: 'Uzbekistan' },
  'Vanuatu': { es: 'Vanuatu', pt: 'Vanuatu', fr: 'Vanuatu', de: 'Vanuatu', it: 'Vanuatu' },
  'Vatican City': { es: 'Ciudad del Vaticano', pt: 'Cidade do Vaticano', fr: 'Cité du Vatican', de: 'Vatikanstadt', it: 'Città del Vaticano' },
  'Venezuela': { es: 'Venezuela', pt: 'Venezuela', fr: 'Venezuela', de: 'Venezuela', it: 'Venezuela' },
  'Vietnam': { es: 'Vietnam', pt: 'Vietnã', fr: 'Vietnam', de: 'Vietnam', it: 'Vietnam' },
  'Yemen': { es: 'Yemen', pt: 'Iêmen', fr: 'Yémen', de: 'Jemen', it: 'Yemen' },
  'Zambia': { es: 'Zambia', pt: 'Zâmbia', fr: 'Zambie', de: 'Sambia', it: 'Zambia' },
  'Zimbabwe': { es: 'Zimbabue', pt: 'Zimbábue', fr: 'Zimbabwe', de: 'Simbabwe', it: 'Zimbabwe' },
};

// Display label for a canonical country name in the given language code.
export function countryLabel(name, lang) {
  if (!name || !lang || lang === 'en') return name;
  return (COUNTRY_I18N[name] && COUNTRY_I18N[name][lang]) || name;
}
